export const allFields = [
	{
		label: '违规编码',
		prop: 'violNo',
		fixed: false,
		required: true,
		sortable: false,
	},
	{
		label: '违规类型',
		prop: 'type',
		fixed: false,
		required: true,
		sortable: false,
		formatter: (row, store) => {
			return row.type?.name || '--';
		},
	},
	{
		label: '违规来源',
		prop: 'source',
		fixed: false,
		required: true,
		sortable: false,
		map: {
			1: '人工巡检',
			2: 'AI巡检',
		},
	},
	{
		label: '违规截图',
		prop: 'imgUrl',
		fixed: false,
		required: true,
		sortable: false,
		isUiImage: true,
		width: '120',
		showOverflowTooltip: false,
	},
	{
		label: '违规说明',
		prop: 'remarks',
		fixed: false,
		required: true,
		sortable: false,
	},
	{
		label: '发现时间',
		prop: 'createTime',
		fixed: false,
		required: true,
		sortable: false,
		dateFmt: 'YYYY-MM-DD HH:mm:ss',
	},
	{
		label: '状态',
		prop: 'state',
		fixed: false,
		required: true,
		sortable: false,
		map: {
			1: '待处理',
			2: '申诉中',
			3: '承建商确认',
			4: '申诉通过',
			5: '撤销',
		},
	},

	{
		label: '所属项目',
		prop: 'projectName',
		fixed: false,
		required: true,
		sortable: false,
		fn: true,
	},
	{
		label: '项目PM',
		prop: 'pmName',
		fixed: false,
		required: true,
		sortable: false,
	},
	{
		label: '申诉意见',
		prop: 'appealComment',
		fixed: false,
		required: true,
		sortable: false,
	},
	{
		label: '申诉时间',
		prop: 'appealTime',
		fixed: false,
		required: true,
		sortable: false,
		dateFmt: 'YYYY-MM-DD HH:mm:ss',
	},
	{
		label: '申诉附件',
		prop: 'appealUrls',
		fixed: false,
		required: true,
		sortable: false,
		dateFmt: 'YYYY-MM-DD HH:mm:ss',
	},
	{
		label: '申诉不通过原因',
		prop: 'appealNotPassComment',
		fixed: false,
		required: true,
		sortable: false,
	},
];
